# Generated by Django 3.2.6 on 2021-08-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlr_latitude', models.FloatField(verbose_name='logradouro')),
                ('vlr_longitude', models.FloatField(verbose_name='bairro')),
                ('cod_munic', models.IntegerField(verbose_name='cidade')),
                ('cod_cnes', models.FloatField(verbose_name='longitude')),
                ('nom_estab', models.CharField(max_length=255, verbose_name='latitude')),
                ('dsc_bairro', models.CharField(max_length=255, verbose_name='nome')),
            ],
        ),
    ]
