# Generated by Django 3.2.6 on 2021-08-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_nome', models.CharField(max_length=255, verbose_name='nome')),
                ('vlr_idade', models.IntegerField(verbose_name='idade')),
            ],
        ),
    ]
